### PR TITLE
Fix conditional check for adding requirements

### PR DESCRIPTION
**Pull request by dizzystuff**
Am I going crazy or does this need to be reversed?

### CODE REVIEW

**Comment by xini** [comment]
It has been that way since the first commit. But from my current understanding, yes. I'll have a look.

**Comment by xini** [comment]
I think the idea was that when the original userforms js is loaded, this module doesn't interfere. Only if you don't want the original, this module will replace them.

I agree that this doesn't make much sense now. If you want the original, simply don't install this module.

This change will need a new major, so I'll have a look what else we could package up with that.

**Comment by dizzystuff** [comment]
Is it possible to merge and tag this one? :)

**Comment by xini** [comment]
@dizzystuff I have reviewed this and have come to the following conclusion: The config setting `block_default_userforms_js` is a config setting of this module to allow the default js for certain UserForm instances. It is set to true by default for `SilverStripe\UserForms\Model\UserDefinedForm` and `DNADesign\ElementalUserForms\Model\ElementForm`, see https://github.com/xini/silverstripe-bundled-userforms/blob/master/_config/config.yml#L5. If you have your own instances that use the `UserForm` trait, you have to configure them accordingly. For these reasons I don't think this PR should be merged. Thoughts?

**Comment by xini** [comment]
Additionally, if we were to swap that check around, no userforms js would be loaded at all, see https://github.com/silverstripe/silverstripe-userforms/blob/6/code/Control/UserDefinedFormController.php#L81. Using it the way the module is using it ensures that either the default or the module's js is loaded.

**Comment by dizzystuff** [comment]
Yeah, with a bit of time away now I can see my original confusion. I didn't understand why `block_default_userforms_js` equalling `true` then included the JS, I think I might even have confused that config var as being part of this module rather than from `userforms`. It's obvious now why this module does apply JS when `block_defualt_userforms_js` is true. The localisation issue is the one to resolve (I'm heading over there now to dig into that convo). Can close this one.

**Comment by xini** [comment]
Thanks.

**Pull request closed without merging**
